
FROM python:3.8.7-slim-buster



ENV CELERY_BROKER_URL='rediss://default:gugzwomvpnhhjgr9@db-redis-fra1-27202-do-user-1010676-0.b.db.ondigitalocean.com:25061/8?ssl_cert_reqs=CERT_REQUIRED'
ENV CELERY_RESULT_BACKEND='rediss://default:gugzwomvpnhhjgr9@db-redis-fra1-27202-do-user-1010676-0.b.db.ondigitalocean.com:25061/9?ssl_cert_reqs=CERT_REQUIRED'
ENV CACHE_REDIS_URL='rediss://default:gugzwomvpnhhjgr9@db-redis-fra1-27202-do-user-1010676-0.b.db.ondigitalocean.com:25061/90?ssl_cert_reqs=CERT_REQUIRED'

ENV CELERY_TASK_RESULT_EXPIRES=300

ENV S3_KEY='SJXBPRS6V3OGYABKNPLE'
ENV S3_SECRET='sOFEW3+TOVPQHwDIMk+5ZDCcgzakyF9T48l4XlzrRA8'

RUN pip install -r requirements.txt


RUN pip install celery



ENTRYPOINT [ "/bin/sh" ]
CMD [ "/docker_start.sh" ]    